name: Publish Docker
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set output
        id: vars
        run: |
          echo ::set-output name=VERSIONTAG::${GITHUB_REF#refs/*/}
          echo ::set-output name=PKGVERSIONTAG::${GITHUB_REF#refs/*/}
      - run: make -e DEVFLAG=false compile build
      - run: docker login docker.pkg.github.com -u $USER -p $PASS
        env:
          USER: ${{ github.actor }}
          PASS: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          export VERSIONTAG=${GITHUB_REF#refs/*/}
          for IMAGE in harbor-core harbor-jobservice; do
            docker tag goharbor/$IMAGE:dev docker.pkg.github.com/flanksource/harbor/$IMAGE:$VERSIONTAG
            docker push  docker.pkg.github.com/flanksource/harbor/$IMAGE:$VERSIONTAG
          done
