name: Publish Docker
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set output
        id: vars
        run: |
          echo ::set-output name=VERSIONTAG::${GITHUB_REF#refs/*/}
          echo ::set-output name=PKGVERSIONTAG::${GITHUB_REF#refs/*/}
      - run: make REGISTRYSERVER=docker.pkg.github.com REGISTRYPROJECTNAME=flanksource REGISTRYUSER=$REGISTRYUSER REGISTRYPASSWORD=$REGISTRYPASSWORD compile build pushimage
        env:
          REGISTRYUSER: ${{ github.actor }}
          REGISTRYPASSWORD: ${{ secrets.GITHUB_TOKEN }}
